steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'compute'
  - 'ssh'
  - 'santhosh@instance-todo1'
  - '--zone'
  - 'us-central1-c'
  - '--command'
  - |
    ls /home/santhosh/main.go
    cd /home/santhosh
    go build main.go
    ./main
options:
  logging: 'CLOUD_LOGGING_ONLY'
